name: QA whole library
on:
  push:
  schedule:
    - cron: "12 1 * * *"
jobs:
  rebuild:
    runs-on: macos-13 # More RAM, heh heh
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: thejerrybao/setup-swap-space@v1
        with:
          swap-space-path: /swapfile
          swap-size-gb: 8
          remove-existing-swap-files: true
      - name: Build fontspector
        run: cargo install --git https://github.com/fonttools/fontspector --features duckdb
      - name: Test all the things
        run: fontspector --profile googlefonts ofl/*/* --succinct --duckdb .ci/fontspector.db -J 4
      - name: Upload results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: .ci/fontspector.db
